### ISSUE TITLE
Coloured output

### ISSUE THREAD

**Issue by simon-p-r** [cmp-202/ssh2shell#17]
Hi

Could there been an option to either display or strip coloured output?  Here is a sample of what is written to console by an ls -ln command

````JS
total 4
drwxrwxr-x. 5 1000 1000 4096 Jun 24 17:01 [01;34mfile
````

This will help when looking at output.

Thanks
Simon

**Comment by cmp-202** [comment]
Hi Simon,
I can definitely do that. There is some cleaning of output but obviously not enough. I will correct the expression and add a flag to the host object.
Cheers,

Andrew

**Comment by woubuc** [comment]
@cmp-202 Any update on this? I'm implementing this module but it seems colours are still not working properly.

**Comment by cmp-202** [comment]
Hi Simon,
Sorry I have been out of action for quite a long time. I will have a look at this early next week once I set up me dev environment again.

**Comment by cmp-202** [comment]
I have added the ability to edit the response text filters by exposing them in the host object. I have added a note to the readme under the prompt detection section. Hopefully this will enable you to turn off textColorFilter regular expression so text is colored in output for you.

**Comment by simon-p-r** [comment]
Thanks I will try it out

**Comment by jgroom33** [comment]
FYI.  The default regex for stripping colors may strip text from the responses.  Here's a behavior I noticed:
```
-------------------------------------------------------------------------------
MAC Address    VLAN/BD/    PEVLAN CEVLAN Port            Type      LSP/LSR-ID
               VSI/SI                                              MAC-Tunnel
-------------------------------------------------------------------------------
9c7a-0338-6a5f saos-127    127    -      GE0/3/6.127     dynamic   3/-         
-------------------------------------------------------------------------------
```
part of a MAC address is stripped from the device response:
```
-------------------------------------------------------------------------------
MAC Address    VLAN/BD/    PEVLAN CEVLAN Port            Type      LSP/LSR-ID
               VSI/SI                                              MAC-Tunnel
-------------------------------------------------------------------------------
-0338- saos-127    127    -      GE0/3/6.127     dynamic   3/-         
-------------------------------------------------------------------------------
```

**Comment by cmp-202** [comment]
I am a bit confused by that because if I copy the expresion (\[[0-9]?[0-9][a-zA-Z]) to a regex test site page and use "9c7a-0338-6a5f saos-127    127    -      GE0/3/6.127     dynamic   3/- " as the test text (no quotes) there is no match which is what I would explect given the \[ in the expression requires [ before the first number. If you set the filter to "" in the host object do you get the full text? Can you give me the command you are using so I can test it.
CHeers,

Andrew

**Comment by jgroom33** [comment]
the command is executed on a Huawei router, so it isn't reproducible.
The following resolved the issue:
```javascript
textColorFilter :"(matchnothing)",
```
When the \[ is removed from the regex as in this link, the behavior is exhibited:
https://regex101.com/r/oB4wX8/1

**Comment by cmp-202** [comment]
If the \\[ is removed that result will be produced but as it is currently present in the filter string so there should be no match in the response text without that [ being present. That doesn't help you though because your output is affected. 

The expression should match the following examples and ignore anything else:
```
[99a
[9a
[9A
[ one or two numbers between 0 to 9 and a letter of lower or uppercase
```

Why that is doesn't fit your case makes no sense to me. I don't know if enabling debug/verbose in the host object would clarify the exact chars that where being matched rather than just seeing the end result. This will be outputed to the console.

This filter being exposed in the host object now enables you to resolve it without a code change but it would be nice to identify why that was happening.

**Comment by cmp-202** [comment]
I think looking at the ansii colouring codes etc for the console I need to do some work on producing an accurate expression based on the standard because I think the current expression is insificient. In the mean time use the solution that is working for you.

**Comment by cmp-202** [comment]
can you try setting filter to:
`textColorFilter :"(\x1b\[[0-9;]*m)",`

**Comment by jgroom33** [comment]
nice work.  That fixes it.

**Comment by cmp-202** [comment]
Hi Simon,
I have added a disableColorFilter boolean paramater to turn the ANSI text formating codes filter on or off.
`host.disableColorFilter: true` will skip running the replace command.
I have left the ability to edit the filter expression in case others are already using it so not to break anything.

This should now resolve this issue, sorry it has taken so long.

Andrew

**Comment by simon-p-r** [comment]
No problem Andrew excellent work :+1:  as always!
