### ISSUE TITLE
Hey, Can't connect to more then one host

### ISSUE THREAD

**Issue by alonbl92456** [cmp-202/ssh2shell#21]
I'm trying to run a bunch of commands on a few  hosts, but during the second host
the session is closed and im getting only little bit of the out put
what should i do ?

**Comment by cmp-202** [comment]
For the session to close I presume the connection has been made for a little bit of output to be returned unless of course the returned info is the connection failure indication. Can you clarify. Is it running any commands at all in that hosts response text? 

Have a look at /test/tunneltest.js to see how I have done it in that example as that is a confirmed method example. 
Also go through the readme looking at the tunneling example, trouble shooting and use verbose host object flag to increase the debug output. Using the debug flag will output every stream onData response which can get ugly but you get to see everything that is happening.

The next option would be to email me at cmp-202@anyzoom.com with your host object and full response text so I can review it and see if there is anything I can find in your method that needs correcting.

**Comment by cmp-202** [comment]
Any progress?

**Comment by alonbl92456** [comment]
Hey,  I managing to connect to one host and run commands, when I'm trying
to do it in a loop it connects to second host , runs some of the commands
and then the session is closed suddenly.
The tunneling option is nice but I don't want to connect from my first host
to the second.
Is there any way to connect and run some commands when I loop through a
list of ip's?

**Comment by cmp-202** [comment]
You could do it in your code by looping through your own array of hosts and recreating the ssh2shell class on each loop. I don't really want to add that to the code simply because it is so easy to do without it and it breaks the paradime. Ssh2shell only makes one connection in reality, each subsequent connection is just a command run from the parent host to the child host to whatever depth. The only thing I think needs to be added is a callback function to the main connect function.

- So make an array of hosts and create your ssh2shell variable then loop through each host.

- On each iteration replace the ssh2shell variable with a new Ssh2shell object and handle the output for that loop. (no callback until I code it)

To debug that second host just do a single host connection to work out what is happening, hjave a look at trouble shooting in readme.
Cheers,

Andrew

**Comment by cmp-202** [comment]
If that doesn't work shift the variable creation to inside the loop to limit the scope. The other approach is to created the ssh2shell object outside the loop and replace the `ssh2shell.sshObj` with the new host object and hit `ssh2shell.connect()` within the loop. More than one way to skin the feline. hope this helps.

**Comment by cmp-202** [comment]
Looking at the event handlers I can't see the point of adding a callback. The event handlers enable multiple functions to be defined for one host object and/or all host objects that will be run whenever that event is triggered. In your case of looping through multiple hosts you would define say the onEnd function and then just set each host.onEnd to the function name (there is your common callback). If you want a unique function for one host just define it on that host object. You can declare multiple onEnd event functions on a host object and all of them will trigger when the event fires. There is some of that in the test files and at the end of the readme.

**Comment by alonbl92456** [comment]
Thanks a lot ! I managed to make it work
