### ISSUE TITLE
SSH Fingerprint Testing

### ISSUE THREAD

**Issue by phpetty** [cmp-202/ssh2shell#22]
Sorry if this is the wrong place to raise this but I couldn't see anywhere else to do it. This is a feature enhancement as the title suggests. 

Would it be possible to add support to:
1) Include the SSH fingerprint of a host in the sshObj after successfully connecting to it.
2) Optionally specify the expected SSH fingerprint for a host in the SSH config - if the expected SSH fingerprint is given and it doesn't match the SSH fingerprint of the host, throw an error/bail.

**Comment by cmp-202** [comment]
HI There,
I think you would be better run a command after connection that requests the key on the server `ssh-keygen -lf /etc/ssh/ssh_host_rsa_key.pub` then use the commandComplete event handler to run a regular experession comparison to extract the key from the responce againt the key you are expecting.
Something like:
```javascript
host = {
   //host object with conection values and other settings//,   
   commands:      [ "ssh-keygen -lf /etc/ssh/ssh_host_rsa_key.pub", "other commands" ],
   onCommandComplete: function( command, response, sshObj ) {
      //if the ssh-keygen command was the last to run check the result
      if (command.indexOf("ssh-keygen") != -1 ) {
         //Extract the fingerprint and compare it against what was expected
         if ( responce.match(/([0-9a-f]{2}:){15}[0-9a-f]{2}$/).indexOf("85:19:8a:fb:60:4b:94:13:5c:ea:fe:3b:99:c7:a5:4e") == -1){
            //raise an error with an appropriate message that closes the connection
            emit('error', 'SSH fingerprint mismatch', 'SSH validation', true, undefined);
         }
      }
   }
}
```
or something like that

**Comment by cmp-202** [comment]
If we can confirm that works I might add it, or the corrected code, to the readme.

**Comment by phpetty** [comment]
Thanks for the prompt reply. I agree that this would work in the general case but I'm looking at this specifically with Cisco devices in mind. When logging into a Cisco device, the SSH fingerprint is shown but this output isn't available to the user of ssh2shell (that I am aware of) and from my research so far the device doesn't provide a CLI/command to directly dump the SSH fingerprint.

**Comment by cmp-202** [comment]
So it isn't outputed to the console (sshObj.response variable) but is outputed as part of the connection response? And there is no way to request it after connection becasue it is the router context.

**Comment by cmp-202** [comment]
this was interesting:
https://learningnetwork.cisco.com/thread/72892

**Comment by phpetty** [comment]
> So it isn't outputed to the console (sshObj.response variable) but is outputed as part of the connection response? And there is no way to request it after connection becasue it is the router context. 

That's correct. I've been reading that page too. Below (from that link) it shows the SSH fingerprint during the login but this is not available in the sshObj as far as I can see:
 _2) SSHing from the linux host to the router
$ ssh root@192.168.127.254
The authenticity of host '192.168.127.254 (192.168.127.254)' can't be established.
RSA key fingerprint is **90:b5:de:97:7a:1f:ca:23:ba:30:7a:0b:d0:47:2c:0**e.
Are you sure you want to continue connecting (yes/no)?_

It looks like it's possible to calculate it based on some router output but if the connection response could be available in the sshObj it would be far simpler.

**Comment by cmp-202** [comment]
I am having trouble with that output because `?` is not considered a standard prompt in the code and the code doesn't handle that yes/no case so it would timeout and disconnect the session. If you are connecting and getting response text (try turning on verbose in the host object to see response text output in your console) then you are not getting that message from the router. The commandProcessing event gives access to check the loading buffer right from the first char so the fingerprint test and the yes/no? promt would be handled there. instead of the event I gave you `onCommandComplete` you would use `onCommandProcessing` with the question prompt test and 'yes' response after it.

**Comment by cmp-202** [comment]
looks like ssh2 has a fingerprint event that I might be able to utilise

**Comment by phpetty** [comment]
I'm not getting anything back on either onCommandComplete or onCommandProcessing until after the login has successfully completed with verbose enabled. Ideally, the fingerprint check should occur before the user has entered their password because if the fingerprints don't match, the user wouldn't want to send their password to a potentially compromised device.

Sounds promising!

**Comment by cmp-202** [comment]
if you ssh to it from the same pc manually do you get it? Might be that connection has already had authenticity of host set which is why the prompt isn't coming up. I think this event is the way to go as it handles it at the lower level and enables the fingerprint to just be another server setting in the host object. The event seems to do the comparison and if it fails the connection is dropped before my code would do anything.

**Comment by phpetty** [comment]
Yeah, I see the prompt when I SSH manually from the same device.

Sounds good - would need to both provide a way to enable this check and also a way to extract the fingerprint following successful login so it can be saved and passed in when the user reconnects.

**Comment by cmp-202** [comment]
Sorry to be a pain can you try turning debug without verbose and tell me what the initial process events are.

**Comment by cmp-202** [comment]
I have created a branch called fingerprint for you to try. I added host.server.hashKey to the server connection variables (see readme) that if set should cause the fingerprint validation to be triggered. So copy the vaild hash from your console into host.server.hashKey and connect then alter the hash and see if it fails. It still doesn't help with collecting the hash in the first place but it is part way there.

**Comment by phpetty** [comment]
I tried running without verbose set and with debug set but I wasn't able to see the events. I sent you an email to the address you have set in git (anyzoom).

master and fingerprint appear to be identical. Have you pushed those changes to fingerprint?
https://github.com/cmp-202/ssh2shell/compare/fingerprint

**Comment by cmp-202** [comment]
Sorry hadn't synced it, changes now uploaded.

**Comment by cmp-202** [comment]
New functionality has been merged into master and the package published to npm. Thanks for your contribution to adding a very good feature like SSH fingerprint validation to ssh2shell.

**Comment by cmp-202** [comment]
Just letting you know I am making a change to hashValidation which will need you to modify your script.
Remember you questioned running the hashValidation everytime so I had another look after exposing all the shh2.connect variables to the host.server confirg and decided to move the function that was in the class to the host.server.hostValidation property. I have added the code to the [readme validation section](https://github.com/cmp-202/ssh2shell#fingerprint-validation) so you can copy that to your script. I droped the hostHash because it is not accessable from within that function, instead I recommend creating a variable at the top level with `var host` and writing to that as in the example.
I also made the error event available to the host object.
