### ISSUE TITLE
When doing 'ls' folder names ending in numbers appear without the number

### ISSUE THREAD

**Issue by IObregon** [cmp-202/ssh2shell#39]
Hi,

I am trying to do a method that returns all the folders in a folder. To achieve this I am executing a cd command and after it an ls command. The problem is that the folders ending in numbers are return without it to the onCommandComplete event.

This is the execution trace with debug and verbose activate:

```
192.168.1.41: Connection.connect
Connected
192.168.1.41: Connection.ready
Ready
192.168.1.41: Connection.shell
192.168.1.41: Normal prompt detected
192.168.1.41: Host.commands: cd nfs1/config-files/,ls
192.168.1.41: Next command from host.commands: cd nfs1/config-files/
192.168.1.41: Notifications: Normal Command to run
192.168.1.41: running: cd nfs1/config-files/
192.168.1.41: Normal prompt detected
192.168.1.41: Command complete:
Command:
 cd nfs1/config-files/
Response:
prueba@iker-To-be-filled-by-O-E-M:~/nfs1/config-files$
192.168.1.41: Raising commandComplete event
cd nfs1/config-files/
prueba@iker-To-be-filled-by-O-E-M:~/nfs1/config-files$
192.168.1.41: Host.commands: ls
192.168.1.41: Next command from host.commands: ls
192.168.1.41: Notifications: Normal Command to run
192.168.1.41: running: ls
192.168.1.41: Normal prompt detected
192.168.1.41: Command complete:
Command:
 ls
Response:
carpeta1  carpeta3  carpeta5  carpeta7  file1
carpeta2  carpeta4  carpeta6  carpeta8  file1.txt
prueba@iker-To-be-filled-by-O-E-M:~/nfs1/config-files$
192.168.1.41: Raising commandComplete event
ls
carpeta  carpeta  carpeta  carpeta  file1
carpeta  carpeta  carpeta  carpeta  file1.txt
prueba@iker-To-be-filled-by-O-E-M:~/nfs1/config-files$
192.168.1.41: No commands so exit
192.168.1.41: Run exit
192.168.1.41: Exit command: Stream: close
192.168.1.41: Stream.finish
192.168.1.41: Class.end
192.168.1.41: Stream.close
192.168.1.41: Connection.close
Closed
```

As you can see, in the response shown before the event, the names are correct.

**Comment by cmp-202** [comment]
Sorry for the long delay in reply the email must have gone to spam, long story, it was lucky I checked the repo.
Can you show your host object with any sensitive information removed.
I am spacifically interested in host.onCommandComplete and any changes to the ascii and text color regular expressions if you have made any.

What is happening in the text above:
The first `Command complete:` with command and response, with the numbers still in it, is displayed when the new prompt is detected after the command is run indicating the end of the command. It is run before any command complete events are raised and before the ascii and text color filtering is applied. Neither of those regular expressions would match your response text to remove the numbers in the onCommandComplete event. Filters can be turned off in the host object if you want to check their impact see readme host object definition.
The onCommandComplete event is raised after filtering some ascii chars and text color codes. The default handler is replaced by host.onCommandComplete if it is defined in the host object otherwise it just displays the host IP and Class.commandComplete text, no response content. 

Just looking at it I don't see any mechanism to strip the numbers in that process apart from the acsii or text color expresions or something in your event handler.

**Comment by cmp-202** [comment]
I am going to presume this is closed

**Comment by IObregon** [comment]
I'm sorry for the delay, I was on vacation.

I don't have the code available now, but I remember that the host.onCommandComplete was only a console.log().

I will try to reproduce it this afternoon at home.

Thanks for your time.

**Comment by cmp-202** [comment]
No problem. Okay we can try turning off the filters to eliminate that option if your hander is just a console.log().
```
host.disableColorFilter = true;
and
host.asciiFilter = [];
```
