### ISSUE TITLE
Triggering commandComplete from commandTimeout

### ISSUE THREAD

**Issue by marcfisher** [cmp-202/ssh2shell#54]
Is there a way in onCommandTimeout that I can trigger it as a complete command and cause it to continue on? Thanks.

**Comment by cmp-202** [comment]
Hi,
So the commandTimeout is triggered when no command prompt is detected after a command finishing sending its output which leaves the session in one of two states: 1) input is required for the command to complete leaving the session hung untill the required input is received. or 2) the command has hung and isn't waiting for input and doesn't return to a prompt.

Note:
The process will naturally continue if you write to the stream and the host responds ending with a command prompt. (This triggers commandComplete)

Case 1) is easy: detect the command and the input prompt in the commandTimeout or commandProcessing and send the required input using stream.write.
For case 2) you may need to send Ctrl-C `stream.write('\x03')` in commandTimeout which cancels the command and returns to the prompt, again resulting in a command complete and the process continues. If any character will return a prompt try `stream.write('\n')`.

There is a third dirty way of proceeding and that is to call `this._commandComplete()` from within the commandTimeout handler but this has no way of knowing if the host is able to continue processing commands because there is clearly no prompt. I wouldn't recommend it unless you have some weird condition that the other methods don't work for.
