### ISSUE TITLE
query regarding callback 

### ISSUE THREAD

**Issue by sidd-harth** [cmp-202/ssh2shell#67]
Hi, this is not an issue. I just have a query regarding Nodejs callback. Any help is appreciated.
I am using below code and was able to connect to my server and execute commands.

Now I want to display the `sessionText` outside the function.
```
var host = {
 server:        {     
  host:         "127.0.0.1",
  userName:     "test",
  password:     "1234",
 },
 commands:      [ "echo $(pwd)", "ls -l" ]
};

var SSH2Shell = require ('ssh2shell'),
  SSH = new SSH2Shell(host),
  callback = function(sessionText){
    console.log(sessionText);
  };

SSH.connect(callback);

//how can I do this? it give undefined
console.log(sessionText)
```

Can I execute the commands `synchronously` without any callbacks and get data from sessionText?

**Comment by cmp-202** [comment]
Hi,
I hope this is what you were asking.
The commands are sequential but not synchronous. This is important because although one command runs after another it is still running asynchronously and event driven. The next command is not sent until no more data events are raised by the stream, identified by a timeout, and a prompt was detected in the last text. 

Because of the asynchronous nature of js you are likely to find that your script can easily terminate or try to access a variable before ssh2shell instance has completed. One line of code after another doesn't mean it will be performed in that order as the second line might complete faster than the first. If the first is running ssh2shell and the second is processing the sessionText then you can see what will happen no sessionText because ssh2shell hasn't completed.

That is why the callback function is one way of providing code to be run when ssh2shell completes. Either through the callback or binding to an event handler your processing of the sessionText is performed when it is actually available and not before.

The other issue is scope within callback/event handler. The scope of the callback is not at the top level where you have defined it but rather within the event within the instance it is run from. Trying to set a variable of code that has terminated or is not relative to what you think it is will give you grief.

So that doesn't give you the answer but the context and I am sure you can find far more accurate info on the net to clarify anything above. 

Solution?
If you can't to it in the callback or event handler:
Add events to your code and have it listening for ssh2shell to raise your event that will process the sessionText and flag that everything is done for your code. You have to be able to wait for ssh2shell to tell you it is done and then process what it has given you.

Hope that is of some sort of help.

**Comment by cmp-202** [comment]
I am closing this one
