### ISSUE TITLE
ssh2shell insufficient buffer size

### ISSUE THREAD

**Issue by sheelaparthanarayana** [cmp-202/ssh2shell#88]
Hi Andrew,

The ssh connection is stopping after X iterations of buffer.
May be it's not properly adding each buffer chunk to the saved variable.
My ssh command is "cat" a large text file, and everytime ssh is closing after printing 34lines(certain number of characters) on command line. If I try to print anything beyond 35lines, then ssh is closing abruptly.

This was not the behavior early but happening from past 2 weeks.

Please help me as to where/how to increase the buffer size ?

Thanks,
Sheela

**Comment by cmp-202** [comment]
Hi Sheela,
Nothing has changed with ssh2shell in the past month.
I presume you are not getting error messages when the connection is closed or anything through turning on debug.
Ssh2shell doesn't have a buffer limit defined specifically, ssh2 does have [Pseudo-TTY](https://github.com/mscdex/ssh2#pseudo-tty-settings) settings defined through `host.window` but the default rows are 24, not 35 so that doesn't seem to apply.
Have you tried running the command manually to confirm it completes with full content, has anything else changed/updated on the server or node two weeks ago? What would be the total char count for your 35 rows.

Andrew
