### ISSUE TITLE
Custom msg handler issue

### ISSUE THREAD

**Issue by juanbor** [cmp-202/ssh2shell#94]
Hey! 

I found that when tyring to [setup a custom msg handler](https://github.com/cmp-202/ssh2shell/blob/9ce29902d41dcfeaddc8a87cc07cc9faeb5908f4/lib/ssh2shell.js#L612), the code validates `typeof this.sshObj.msg === 'function'`. I was wondering if the validation should be `typeof this.sshObj.msg.send === 'function'` instead in order to something like `msg:                {
    send: function( message ) {
      console.log(message);
    }
  },` can work.

Thanks and I'll happy to submit a pr if that's the case.

**Comment by cmp-202** [comment]
It's actually a throwback to a `msg.send` command in hubot where `msg` was passed to ssh2shell and sshObj.msg.send was called for hubot output instead of console output.
There are probably 3 cases: default using console (no host definition), host.msg defined using just `msg()` and host.msg defined but using `msg.send()`.
I have pushed an update to the repo /lib/ssh2shell.js give it a try and let me know if it fixes it for you.
Thanks,

Andrew

**Comment by juanbor** [comment]
Thanks for the quick response!

I just tried it and that update worked perfectly for me

**Comment by cmp-202** [comment]
nice no problem

**Comment by juanbor** [comment]
Also, is there any plan to make a new release with these changes?

**Comment by cmp-202** [comment]
Yes I need to do testing first and then I will publish to npm.

**Comment by juanbor** [comment]
Great! Thanks!

**Comment by cmp-202** [comment]
published finally v1.9.10
